name: github_repo_search
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  json_serializable: ^6.7.1
  pedantic_mono: any
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
